### ISSUE TITLE
examples failure

### ISSUE THREAD

**Issue by jflynn129** [attm2x/m2x-arm-mbed-mqtt#1]
I've built the example programs and tried them multiple times and when I run it I get the following:
I then used the same M2X Key and Device ID with your library and when I
run it, it says (I turned DEBUG on):
postDeviceUpdates...
Connected to M2X MQTT server!
CONNACK return code is not accepted: 5
ERROR: Cannot connect to M2X server!
Response code: -1

updateLocation...
Connected to M2X MQTT server!
CONNACK return code is not accepted: 5
ERROR: Cannot connect to M2X server!
Update response code: -1

Current temperature is: 1.000000
updateStreamValue (temp)...
Connected to M2X MQTT server!

To verify that M2X was infact working, I used CURL:
curl -i
"http://api-m2x.att.com/v2/devices/e83cdd8645ab1a7c0c480156efbf78f6/streams/temperature"
-H "X-M2X-KEY: 4d7e1da7f05c3fa4d5426419891a254d" -H "Accept:
application/x-msgpack"
HTTP/1.1 200 OK
Content-Type: application/x-msgpack
Date: Fri, 09 Sep 2016 11:55:29 GMT
Server: nginx
Vary: Accept-Encoding
Vary: Accept
X-M2x-Version: v2.99.1
Content-Length: 312

��name�temperature�display_name�temperature�value�0.1�latest_value_at�2016-09-09T02:19:17.709Z�type�alphanumeric�unit��label�degree
Fahrenheit�symbol�°F�url�Vhttp://api-m2x.att.com/v2/devices/e83cdd8645ab1a7c0c480156efbf78f6/streams/temperature�created�2016-08-11T01:05:29.226Z�updated�2016-08-11T01:05:29.226Z

So I know M2X is working, but for some reason the MQTT library isn't.  I wasn't able to determine what a return code "5" meant.

Any Help?

**Comment by kristinpeterson** [comment]
@xxuejie when you have a moment, can you assist with this?

**Comment by jflynn129** [comment]
Kristin, I wanted to check with you. Are you the person that is
responsible for the AT&T mbed libraries?  I was trying to find
someone/somehow to report a bug on the
https://developer.mbed.org/teams/ATT-M2X-team/code/M2XStreamClient/
library but couldn't find it on github anywhere (only on the mbed site).
 Do you know anything about how to report a problem on that site?  If
your not the right person, sorry to bother you.  I can also check with
ARM since they are the mbed.org owners but was going to try you first.

/Jim

**Comment by jflynn129** [comment]
BTW, just in case you can help, here is the information/problem I
encountered:


Problem: When performing a readLocation call using the M2XStreamClient
library, the call hangs and never returns.

Investigation:
I have a large amount of data in my Location store on M2X
(https://m2x.att.com/devices/e83cdd8645ab1a7c0c480156efbf78f6).  When I
call the readLocation method, and it never returns.
Problem:
The problem is when readLocation is called, it expects a
“Content-Length:” header in the M2X server response.  But the M2X
response does not include this header, so as a result, the program just
hangs.  A copy of the M2X response is below.
Possible Solutions:
1. Insert a read-timeout in the ‘readContentLength’ function so it
doesn’t hang forever.
2. Check with the M2X server guys and confirm that this response is
correct (no Content-Length header).  It may be a problem in their code.

Response received that is missing “Content-Length”
---------------------------
Content-Type: application/json; charset=UTF-8
Date: Sat, 10 Sep 2016 21:53:34 GMT
Server: nginx
Vary: Accept-Encoding
Vary: Accept
X-M2x-Version: v2.99.2

{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T21:53:33.817Z","waypoints":[{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T21:53:33.817Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T21:50:01.028Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T21:40:38.061Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T21:31:31.009Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T21:27:54.698Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T21:18:11.895Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T21:13:54.558Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T21:11:02.413Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T21:06:45.441Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T20:51:06.037Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T20:46:14.902Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T20:41:14.399Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T20:39:18.270Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T20:33:27.345Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T20:25:15.459Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T20:17:32.574Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T20:12:25.781Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T20:03:58.228Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T20:01:00.651Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T19:59:08.666Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T19:56:11.988Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T19:47:36.097Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T19:02:38.699Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T19:00:39.447Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T18:58:31.856Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T18:54:17.569Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T18:50:55.032Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T18:44:47.682Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T18:43:20.067Z"},{"name":"Wake
Forest","latitude":33.0079,"longitude":-96.7516,"elevation":"697","timestamp":"2016-09-10T18:40:36.892Z"}]}

**Comment by kristinpeterson** [comment]
@jflynn129 Thanks for reporting the issue! That appears to be our mbed HTTP library, while this is the repository for the mbed MQTT library. Issues relating to the mbed HTTTP library can be reported here: https://github.com/attm2x/m2x-arm-mbed/issues

I've created an issue based on the information provided in your two most recent comments, we can continue the discussion regarding that particular issue here: https://github.com/attm2x/m2x-arm-mbed/issues/5

**Comment by xxuejie** [comment]
@jflynn129 Hah I did remember seeing your email on Friday to my personal email address, sorry I've had a busy Friday so I didn't reply in time...

So for the first example, a response of `-1` means a network problem, it's either the board cannot connect to the Internet, or it does not receive response in time from M2X. Could you first check if this is the case?

Also since your other issue mentioned that `readLocation` hangs, maybe you did have connection to the Internet, correct? Could you check if the example is still this case?

**Comment by jflynn129** [comment]
Hi, I got the network response resolved.  Now when
mmqtt_s_decode_connack_header is called it returns with a status of
MMQTT_STATUS_OK but the connack_header.return_code is set to 5.

What would cause such an error?

**Comment by xxuejie** [comment]
`5` means the connection is not [authorized](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718035), are you sure that you have provided the correct M2X key?

**Comment by jflynn129** [comment]
Thank you for that explanation.  Where can you get such information from
(do you have a URL to it?).

This aspect is very confusing. There are the following keys:
1) Device ID
2) Primary Endpoint
3) Primary API key
4) Master Key

I have tried the device key (which is obvious), but the m2xKey is not
clear.  Is it the Master Key or the Primary API key.  I have tried both
and they both work the same way (return error code of 5).  Is there some
other Key I should be using?  Does the m2x.att.com account have to be
enabled to support MQTT operation?

**Comment by jflynn129** [comment]
I have posted the program I am using at:
https://developer.mbed.org/users/JMF/code/m2x-arm-mqtt-jmf/

I have all my keys listed in comments above the defines.  I have tried
all these keys and I always get the following response when it is run:

IP Address: 192.168.0.245
Current temperature is: 1.000000
updateStreamValue (temp)...
Connected to M2X MQTT server!
CONNACK return code is not accepted: 5
ERROR: Cannot connect to M2X server!
Response code: -1
Current humidity is: 100.000000
updateStreamValue (humid)...
ERROR: Cannot connect to M2X MQTT server!
ERROR: Cannot connect to M2X server!
Response code: -1

So the initial response is always:
Connected to M2X MQTT server!
CONNACK return code is not accepted: 5

I have debugged it a little, and whatever is happening seems to be
happening when it is decode the connack header.  Can you try and repro
this problem in your environment and let me know if it works for you?

I'm not doing anything different from your posted example except I am
running on a FRDM-K64F.

/Jim

**Comment by jflynn129** [comment]
Some additional information that may be helpful.  When I am trying to run
this demo program, even though it says it is failing, if I go to the
m2x.att.com Dashboard and look at the API Request Log History, I can see
the traffic that has been sent (even though the library is telling me it
failed):

*200* GET /devices/8bcfff8a8514678f0fc6b56cb0f55c87/streams/humidity/values
09/13/2016
21:06:43 EDT
*200* GET /devices/8bcfff8a8514678f0fc6b56cb0f55c87/streams/humidity/values
09/13/2016
21:06:43 EDT
*204* GET /devices/8bcfff8a8514678f0fc6b56cb0f55c87/location 09/13/2016
21:06:42 EDT
*200* GET /devices/8bcfff8a8514678f0fc6b56cb0f55c87/triggers/ 09/13/2016
21:06:41 EDT
*200* GET /devices/8bcfff8a8514678f0fc6b56cb0f55c87/streams/ 09/13/2016
21:06:41 EDT
*200* GET /devices/8bcfff8a8514678f0fc6b56cb0f55c87 09/13/2016 21:06:39 EDT

**Comment by kristinpeterson** [comment]
@jflynn129 the items you're seeing in the API Request Log appear to all be `GET` requests, and they are caused by the M2X Developer Portal UI making requests to display your data. Thus, these requests do not indicate that the device was able to successfully send data to M2X.

The code sample you've provided indicates that you've passed the `Primary API Key` as the `Device ID` value. Can you update the `deviceId` variable to use the Device ID and try again?

**Comment by xxuejie** [comment]
@jflynn129 Okay so after some research I can replicate what you are seeing, working on a fix now.

**Comment by xxuejie** [comment]
@jflynn129 Okay so there is a bug and I've already fixed it. I also tested and now it works. Now you can update the library you use and it should be working. Feel free to let us know if you have any more questions.

Sorry about the trouble caused.

**Comment by jflynn129** [comment]
Hi, just wanted to let you know that I updated and everything is working
like it says it should for me.  Thanks!

/Jim

**Comment by kristinpeterson** [comment]
Excellent! Thank you for the fix @xxuejie & thanks for reporting the issue @jflynn129 

I'll close out this ticket, as it appears all issues reported here have been resolved. Feel free to reopen if I'm mistaken.

**Comment by jflynn129** [comment]
Hi Richard & Kristin,  I have been looking into some problems we are having with a M2X MQTT demo which uses M2XMQTTClient, Minimal-mqtt, and minimal-json.  I’m not sure exactly what is happening since I’m not intimately familiar with the library code, but I have collected some logs with basic debug info and attached it with hopes you could get someone to investigate it a bit and let me know if the problem is in the citrusbyte libraries.
 
I am using the code that is at https://developer.mbed.org/teams/Avnet/code/WNCInterface_M2XMQTTdemo/ .  The code simply uploads data to the M2X site, waits a short period, then sends data again.  It does this over and over forever.  I ran this code over this past weekend and captured the attached results.  The number of executions was 2038, 1349, 522, 42, and 7.  It seems that when the failures occur, the protocol is looking to collect some data that either hasn’t been received, or is just unusual (negative numbers).  My initial guess was a bug in the data queues, but it seems too inconsistent for that.  After looking at it a bit, I was thinking maybe some data in the incoming message was corrupt, resulting in an incorrect message length in the MQTT message.  I’m hoping that if someone who is more familiar with the protocol libraries will be able to identify the issue.  All the data sent & received is listed in the attached logs.
 
Could you have someone look this data over and give me their opinion on the issue.

**Comment by jflynn129** [comment]
In the data log that ran the longest, the last entry is as follows:
Sending readings #2038
[*] -1329979452 <-------- Begin Cell Status ------------
[*] -1329979072 TX: AT+CSQ
[*] -1329973279 RX: AT+CSQ+CSQ: 18,0OK
[*] -1329972990 TX: AT+CPIN?
[*] -1329966784 RX: AT+CPIN?+CPIN: READYOK
[*] -1329966476 TX: AT+CREG?
[*] -1329959094 RX: AT+CREG?+CREG: 2,1,2717,0BAA1410,7OK
[*] -1329958703 ------------ WNC Ready ---------------->
[*] -1329958326 TX: AT@SOCKWRITE=1,128,"**30e701002d6d32782f33643166336330663432613863353431323035663730366636326336353333302f72657175657374737b226964223a2238313439222c226d6574686f64223a22505554222c227265736f75726365223a222f76322f646576696365732f3862636666663861383531343637386630666336623536636230**"
[*] -1329881219 RX: AT@SOCKWRITE=1,128,"30e701002d6d32782f33643166336330663432613863353431323035663730366636326336353333302f72657175657374737b226964223a2238313439222c226d6574686f64223a22505554222c227265736f75726365223a222f76322f646576696365732f3862636666663861383531343637386630666336623536636230"@SOCKWRITE:128OK
**In decode_buffer, buffer_length=1
connection_read_stream_length() ok, consume_length=1

JMF:here! [asking for 1 bytes]
available() has no data, try to fill in...**
[*] -1329861100 <-------- Begin Cell Status ------------
[*] -1329856406 TX: AT+CSQ
[*] -1329848807 RX: AT+CSQ+CSQ: 19,0OK
[*] -1329848523 TX: AT+CPIN?
[*] -1329842152 RX: AT+CPIN?+CPIN: READYOK
[*] -1329841846 TX: AT+CREG?
[*] -1329834376 RX: AT+CREG?+CREG: 2,1,2717,0BAA1410,7OK
[*] -1329833980 ------------ WNC Ready ---------------->
[*] -1329831410 TX: AT@SOCKWRITE=1,106,"6635356338372f73747265616d732f74656d70657261747572652f76616c7565222c226167656e74223a22557365722d4167656e743a204d3258204d626564204d51545420436c69656e742f302e312e30222c22626f6479223a7b2276616c7565223a22362e33227d7d"
[*] -1329754999 RX: AT@SOCKWRITE=1,106,"6635356338372f73747265616d732f74656d70657261747572652f76616c7565222c226167656e74223a22557365722d4167656e743a204d3258204d626564204d51545420436c69656e742f302e312e30222c22626f6479223a7b2276616c7565223a22362e33227d7d"@SOCKWRITE:106OK
**_fillin(), tmp=128**
[*] -1329751796 TX: AT@SOCKREAD=1,128
[*] -1329735185 RX: AT@SOCKREAD=1,128@SOCKREAD:0,""OK
[*] -1329252080 TX: AT@SOCKREAD=1,128
[*] -1329238534 RX: AT@SOCKREAD=1,128@SOCKREAD:0,""OK
[*] -1328752078 TX: AT@SOCKREAD=1,128
[*] -1328738496 RX: AT@SOCKREAD=1,128@SOCKREAD:0,""OK
[*] -1328252077 TX: AT@SOCKREAD=1,128
[*] -1328238530 RX: AT@SOCKREAD=1,128@SOCKREAD:0,""OK
**available(), _incnt=0
JMF:while done [returning 0 bytes, asked for 1 bytes]
>>>>>>>>>>>>>>>>>>********************************

**In decode_buffer, buffer_length=1
connection_read_stream_length() ok, consume_length=1

JMF:here! [asking for 1 bytes]
available() has no data, try to fill in...
_fillin(), tmp=128**
[*] -1328228298 TX: AT@SOCKREAD=1,128
[*] -1328212099 RX: AT@SOCKREAD=1,128@SOCKREAD:0,""OK
[*] -1327728586 TX: AT@SOCKREAD=1,128
[*] -1327715241 RX: AT@SOCKREAD=1,128@SOCKREAD:0,""OK
[*] -1327228578 TX: AT@SOCKREAD=1,128
[*] -1327195175 RX: AT@SOCKREAD=1,128@SOCKREAD:105,"3067002E6D32782F33643166336330663432613863353431323035663730366636326336353333302F726573706F6E7365737B226964223A2238313439222C22737461747573223A3230322C22626F6479223A7B22737461747573223A226163636570746564227D7D"OK
[*] -1327192273 TX: AT@SOCKREAD=1,23
[*] -1327178352 RX: AT@SOCKREAD=1,23@SOCKREAD:0,""OK
**available(), _incnt=105
JMF:while done [returning 1 bytes, asked for 1 bytes]
In decode_buffer, buffer_length=2
connection_read_stream_length() ok, consume_length=2

JMF:here! [asking for 2 bytes]
available(), _incnt=104
available(), _incnt=103
JMF:while done [returning 2 bytes, asked for 2 bytes]
In decode_buffer, buffer_length=0
connection_read_stream_length() ok, consume_length=26368**

ASKING FOR 0 / max_size = 0!!!!



It is strange that consume_length is now 26368 bytes.  In other transactions, I see that the request is -14 and the buffer_length is -14.  This is why I suspected a ring buffer issue but if you decode the message data (that is hex encoded ASCII) it messages all look reasonable.

**Comment by kristinpeterson** [comment]
Here is a zip file with more output data: https://cl.ly/2S001i0h3h1B
